version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongodb
    volumes:
      - ./.env:/app/.env:r
    networks:
      - quizmaster-network

  frontend:
    container_name: frontend
    build:
      context: ./src/main/resources/frontend/quizmaster
      dockerfile: Dockerfile
#    ports:
#      - "4200:80"
    depends_on:
      - backend
    networks:
      - nginx-network
      - quizmaster-network

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./.env:/docker-entrypoint-initdb.d/.env:r
    networks:
      - quizmaster-network

volumes:
  mongo-data:

networks:
  quizmaster-network:
  nginx-network:
    external: true