version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongodb
    volumes:
      - ./.env:/app/.env:r

#  frontend:
#    build:
#      context: ./src/main/resources/frontend/quizmaster
#      dockerfile: Dockerfile
#    ports:
#      - "4200:4200"
#    depends_on:
#      - backend

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./.env:/docker-entrypoint-initdb.d/.env:r

volumes:
  mongo-data: