spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASS}@quizmaster-mongodb:27017/quizmaster?authSource=admin
      authentication-database: admin

  liquibase:
    enabled: true
    url: mongodb://${MONGO_USER}:${MONGO_PASS}@quizmaster-mongodb:27017/quizmaster?authSource=admin
    change-log: db/changelog/changelog-master.xml

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true